title: Starry Log
description: Kepvisha's Personal Blog
baseurl: "" # Keep empty if using a custom domain or username.github.io
url: "https://yourusername.github.io"
theme: null # We are building a custom theme, so set this to null

markdown: kramdown
permalink: /:year/:month/:day/:title/
